name: flutter_frenzy_multi_threading
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  google_fonts: ^4.0.4
  image: ^4.0.17
  path_provider: ^2.0.15
  rive: ^0.11.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

import_sorter:
  comments: false
  # ignored_files:
  #   - \/lib\/*
